### ISSUE TITLE
Hello, sir

### ISSUE THREAD

**Issue by planetweed** [Vegann/valorant_daily_store#3]
I was looking for the API using Ruby so This API is so helpful for me.
May I get some more usage? testing/assuming but it doesn't work 
<img width="985" alt="スクリーンショット 2022-07-21 19 53 51" src="https://user-images.githubusercontent.com/109707512/180197707-efffdc2c-cb0b-4440-ad62-7bd39dfa8eca.png">

**Comment by Vegann** [comment]
Hello there,
```shell
valorant_daily_store get -u "test" -p "test" -r "apac"
```
Have to be executed in the shell.
If you want to run it in the ruby console/script, you have to use it like this:
```ruby
ValorantDailyStore.get_data(region: "apac", username: "test", password: "test")
```
